backend:
  name: git-gateway
  repo: fujband/fujband
  branch: master
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "public/media/uploads"
public_folder: "/media/uploads"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "songs"
    label: "Songs"
    label_singular: "Song"
    create: true
    delete: false
    editor:
      preview: true
    folder: "content/songs"
    slug: "{{slug}}"
    fields:
        - {label: Title, name: title, widget: string}
        - label: "Status"
          name: "status"
          widget: "select"
          options: ["Published", "Draft", "Hidden"]
          defualt: "Published"
        - {label: Date / Order, name: date, widget: date}
        - {label: Text, name: text, widget: markdown}